config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'trips#index'

  resources :trips do
    resources :locations
  end

  get '/new_no_nest', to: 'locations#new_no_nest', as: 'new_no_nest'
  post '/no_nest_create', to: 'locations#no_nest_create', as: 'no_nest_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip, optional: true
end

app/models/trip.rb
class Trip < ApplicationRecord
	has_many :locations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #justin
  before_action :authenticate_user!
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :location_set, only: [:edit, :update, :destroy]
  before_action :trip_set, except: [:new_no_nest, :no_nest_create]

  def new
    @locations = Location.all
    @location = @trip.locations.new
  end

  def new_no_nest
    @location = Location.new
    @trips = Trip.all
  end

  def create
    @location = @trip.locations.new(location_params)
    if @location.save
      flash[:success] = Faker::StarWars.quote
      redirect_to trip_path(@trip)
    else
      render 'new'
    end
  end

  def no_nest_create
    @location = Location.new(location_params)
    if @location.save
      flash[:success] = Faker::StarWars.quote
      redirect_to trips_path
    else
      render 'new_no_nest'
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      flash[:success] = Faker::StarWars.quote
      redirect_to trip_path(@trip)
    else
      render 'edit'
    end
  end

  def destroy
      @location.destroy
      flash[:danger] = "Strike me down, and I will become more powerful than you could possibly imagine."
      redirect_to trip_path(@trip)
  end

  private
    def location_set
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:name, :address, :trip_id)
    end

    def trip_set
      @trip = Trip.find(params[:trip_id])
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = Trip.all.order('created_at DESC')
  end

  def show
    @locations = @trip.locations.order( 'created_at ASC' )
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      flash[:success] = Faker::StarWars.quote
      redirect_to trip_path(@trip)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      flash[:success] = Faker::StarWars.quote
      redirect_to trip_path(@trip)
    else
      render 'edit'
    end
  end

  def destroy
    @trip.destroy
    flash[:danger] = "Strike me down, and I will become more powerful than you could possibly imagine."
    redirect_to trips_path
  end

  private
    def trip_params
      params.require(:trip).permit(:trip_name, :trip_duration)
    end

    def set_trip
      @trip = Trip.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripTrackr</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- NavBar -->
    <nav class="navbar navbar-expand-lg bg-dark">

      <div class="navbar-brand">
        <%= link_to trips_path, id:'logo-link' do %>
          <%= image_tag(('logo-nav-bar.png'), id: 'nav-logo-img') %>
        <% end %>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapseNavbar">
        <i class="fa fa-bars fa-lg"></i>
      </button>

      <div class="collapse navbar-collapse" id="collapseNavbar">
        <ul class="navbar-nav">
          <li class="nav-item mr-4">
            <%= link_to 'All', trips_path, class: 'nav-link' %>
          </li>
          <li class="nav-item mr-2 dropdown">
            <a href="#" class="nav-link dropdown-toggle", data-toggle="dropdown">New</a>
            <!-- <%= link_to 'New', new_trip_path , class: 'nav-link dropdown-toggle', 'data-toggle':'dropdown'%> -->
            <div class="dropdown-menu bg-dark">
              <%= link_to 'New Adventure', new_trip_path, class:'dropdown-item dd-link' %>
              <%= link_to 'New Stop', new_no_nest_path, class: 'dropdown-item dd-link' %>
            </div>
          </li>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </ul>
      </div>

    </nav>

    <!-- Flash Messages -->
    <% flash.each do |key, value| %>
      <div class="text-center alert alert-<%= key %>">"<%= value %>"</div>
    <% end %>
    <%= yield %>

    <footer class="bg-dark text-center">
      Made by <a href="https://github.com/isabeljulmar" target="_blank">Isabel Martin</a>, <a href="https://github.com/gadzooks25" target="blank_">Justin Dean</a>, and <a href="https://github.com/maxwinslow" target="blank_">Max Winslow</a> for DevPoint Labs
      <audio class='hey bg-dark' controls>
      <source src="/star-wars-theme.mp3" type="audio/mp3">
      </audio>
    </footer>

  </body>

</html>

app/views/locations/edit.html.erb
<div class="container mt-5 text-center">
  <h1 class="mb-5"><%= @location.name %></h1>

  <%= form_for [@trip, @location], class: 'form-group' do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control bg-dark text-white text-center my-5', required: true, autofocus: true %> <br> <!--RAS-->
    <%= f.label :address %>
    <%= f.text_area :address, class: 'form-control bg-dark text-white text-center' %> <br><!--RAS-->
    <%= f.submit nil, class: 'btn btn-warning text-white mt-3 form-link' %>
  <% end %>

  <%= link_to 'Go Back', trips_path, class: 'btn btn-danger text-white mt-3 form-link' %>
</div>

app/views/locations/new.html.erb
<div class="container mt-5 text-center">
  <h1 class="mb-5">Add Stop to "<%= @trip.trip_name %>"</h1>

  <%= form_for [@trip, @location], class: 'form-group' do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control bg-dark text-white text-center my-4 options', list: 'locations', required: true, autofocus: true, autocomplete: 'off' %>
    <%= f.label :address %>
    <%= f.text_area :address, class: 'form-control bg-dark text-white text-center' %>
    <%= f.submit nil, class: 'btn btn-warning text-white mt-3 form-link' %>
  <% end %>

  <datalist id="locations">
    <% @locations.all.each do |l| %>
      <option value="<%= l.name %>"><%= l.name %><%= l.address %></option>
      <% end %>
  </datalist>

  <%= link_to 'Go Back', trips_path, class: 'btn btn-danger text-white mt-3 form-link' %>
</div>

app/views/locations/new_no_nest.html.erb
<div class="container mt-5 text-center">
  <h1 class="mb-5">New Stop</h1>
  <%= form_for @location, url: no_nest_create_path(@location), class: 'form-group' do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control bg-dark text-white text-center my-4', list: 'locations', required: true, autofocus: true, autocomplete: 'off'  %>
    <%= f.label :address %>
    <%= f.text_area :address, class: 'form-control bg-dark text-white text-center' %>
    <%= f.select :trip_id, @trips.collect { |t| [t.trip_name, t.id] }, {}, class: 'form-control bg-dark my-4 text-white' %>
    <%= f.submit nil, class: 'btn btn-warning text-white mt-3 form-link'  %>
  <% end %>
  <%= link_to 'Go Back', trips_path, class: 'btn btn-danger text-white mt-3 form-link' %>
</div>

app/views/trips/_form.html.erb
<%= form_for @trip, class: 'form-group' do |f| %>
  <%= f.label :trip_name, 'Adventure Name' %>
  <%= f.text_field :trip_name, class: 'form-control bg-dark text-white text-center', required: true, autofocus: true, autocomplete:'off', placeholder: 'The force will be with you... always' %> <br>
  <%= f.label :trip_duration, 'Duration' %>
  <%= f.number_field :trip_duration, class: 'form-control text-right bg-dark text-white text-center', required: true%> <div class="text-center"><em>Parsecs</em></div> <br>
  <%= f.submit nil, class: 'btn btn-warning text-white mt-3 form-link' %>
<% end %>

<%= link_to 'Go Back', trips_path, class: 'btn btn-danger text-white mt-3 form-link' %>

app/views/trips/edit.html.erb
<div class="container mt-5 text-center">
  <h1><%= @trip.trip_name %></h1>
  <%= render 'form' %>
</div>

app/views/trips/index.html.erb
<div class="container d-flex star-wars" id="index-container">

  <div class="yoda">
  <%= image_tag(('yoda.png'), id: 'yoda') %>
  </div>

  <div id="resize" class="mx-auto crawl">
    <h1 class="trips-index text-center">Active Adventures</h1>
    <ul class="list-group text-center">
      <% @trips.each do |trip| %>
        <%= link_to(trip_path(trip), class: 'list-item') do %> <br>
          <%= trip.trip_name %> |
          <%= trip.trip_duration %> parsecs
        <% end %>
      <% end %>
    </ul>
  </div>

</div>

app/views/trips/new.html.erb
<div class="container mt-5 text-center">
  <h1>New Adventure</h1>
  <%= render 'form' %>
</div>

app/views/trips/show.html.erb
<div class="container">

  <div class="text-center mt-5">
    <h2><%= @trip.trip_name %></h2>
    <h4 class='mb-4'><%= @trip.trip_duration %> parsecs</h4>
  </div>

  <nav class="navbar navbar-expand-sm bg-default d-flex row justify-content-around", id='trip-nav-show'>
    <ul class="navbar-nav">
      <li class="nav-item px-5">
        <%= link_to 'Add Stops', new_trip_location_path(@trip), class:'nav-link' %>
      </li>
      <li class="nav-item px-5">
        <%= link_to 'Edit', edit_trip_path(@trip), class: 'nav-link' %>
      </li>
      <li class="nav-item px-5">
        <%= link_to 'Delete', trip_path(@trip), method: :delete, data: { confirm: 'Are you sure?' }, class: 'nav-link' %>
      </li>
      <li class="nav-item px-5">
        <%= link_to 'Back', trips_path, class: 'nav-link' %>
      </li>
    </ul>
  </nav>

  <h3 class='text-center mt-5'>Itnerary</h3>
  <table class="table table-striped table-dark my-5 text-center">
    <thead>
      <tr id='location-table-head'>
        <th scope="col">Stop #</th>
        <th scope="col">Name</th>
        <th scope="col">Address</th>
      </tr>
    </thead>
    <tbody>
      <% num = 1 %>
      <% @locations.each do |location| %>
        <tr>
          <th scope='col'><%= num  %></th>
          <td><%= location.name %></td>
          <td><%= location.address %></td>
          <td>
          <div class="edit-destroy-icons">
            <%= link_to '<i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i>'.html_safe, edit_trip_location_path(@trip, location),
            class: 'delete-icon' %>
            <%= link_to '<i class="fa fa-trash fa-lg" aria-hidden="true"></i>'.html_safe, trip_location_path(@trip, location), method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
          </td>
        </tr>
        <% num += 1 %>
      <% end %>
    </tbody>
  </table>

</div>